### ISSUE TITLE
[US01] - Cadastro de Usuário

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#15]
### Descrição:
Eu, como	Alessandra, desejo	poder cadastrar um novo usuário no Schedula, para permitir que um novo colaborador acesse o Schedula.

### Tarefas:

- [x] Endpoint de criação de usuário
- [x] Endpoint de edição de usuário
- [x] Endpoint de leitura de usuários
- [x] Endpoint de exclusão de usuários
- [ ] Alterar endpoints criados no frontend

### Critérios de aceitação:

- Os endpoints deverão seguir o padrão REST;
- A senha do usuário deve ser protegida com criptografia;
- Deve existir atribuição de cargo para o usuário;
- CI estar passando ;
- Respeitar todas as orientações acima.

**Comment by guilhermepupak** [comment]
**Critérios de aceitação**

Sugerimos trocar o nome da US para **US 01 - Cadastro de Usuário**.

1. O usuário poderá logar na Aplicação tanto pelo **Nome de Usuário** ou pelo **E-mail**;
2. O cargo do usuário é apenas uma informação do usuário, não irá determinar nenhum privilégio dentro da Aplicação (Cargos: Coordenador, Chefe, Gerente, Escrivão, Agente, Delegado, Administrativo, Comissionado e Estagiário);
3. O PERFIL do usuário irá determinar seu privilégio dentro da Aplicação, podendo ser:

    Administrador (Consultar ; Cadastrar; Editar; Excluir);
    Atendente (Consultar ; Cadastrar e Editar apenas os seus registros);
    Consulta (apenas Consultar).

4. O Administrador irá colocar um senha aleatória, porém no momento do primeiro login do usuário, a aplicação solicitará que o usuário troque a senha. Obs.: Com a possibilidade de cadastrar um **senha definitiva** para o usuário com perfil de **CONSULTA**.


A tela de Cadastro de usuário poderá ser igual a esta imagem abaixo, contudo, nas cores já definidas pela equipe do semestre passado (2/2021):
![image](https://user-images.githubusercontent.com/109108065/206202372-8c7a781f-489d-48a8-87ae-ea0b6c06a204.png)
