### ISSUE TITLE
[US05] - Cadastro de Agendamentos

### ISSUE THREAD

**Issue by matgomes21** [fga-eps-mds/2022-2-Schedula-Doc#17]
### Descrição:

Eu, como	Alessandra, desejo poder cadastrar um agendamento de um chamado, para controlar as visitas técnicas.

### Tarefas:

- [ ] Endpoint de criação de agendamento
- [ ] Endpoint de leitura de agendamentos
- [ ] Endpoint de leitura de agendamento específico
- [ ] Endpoint de edição de agendamento
- [ ] Endpoint de exclusão de agendamento
- [ ] Alterar rotas chamadas pelo frontend

### Critérios de aceitação:

- Endpoints seguindo padrão REST
- Filtros disponíveis
- CI/CD passando

**Comment by guilhermepupak** [comment]
**Critérios de aceitação**

**CONCEITO**: De forma geral, o Agendamento, nada mais é do que um atendimento telefônico que não foi possível resolver por telefone/remotamente e, nesse caso, este atendimento terá que ser agendado para uma visita do técnico ao local. Além disso, existe os casos de Eventos, em que há a necessidade de um Unidade de Policia Civil no local, por exemplo, Pecuárias, Estádios de Futebol, Shows, Eventos Sociais da Prefeitura... etc
