### ISSUE TITLE
[US06] - Cadastro de cidades

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#35]
### Descrição:
Eu, como Alessandra, desejo poder cadastrar uma cidade, para gerenciar as cidades onde estarão os postos de controle.

### Tarefas:

- [ ] Desenvolver CRUD da aplicação
- [ ] Criar os testes unitários relacionados ao CRUD

### Critérios de aceitação:

- [ ] Alessandra deverá poder cadastrar uma nova cidade
- [ ] A cidade deve ser uma cidade real do Brasil
- [ ] A cidade deverá estar relacionada com seu estado
- [ ] Não pode haver cidades duplicadas
- [ ] Alessandra deverá poder remover uma cidade da aplicação
- [ ] Alessandra deverá poder editar uma cidade
- [ ] O usuário deve poder pesquisar a cidade pelo nome
- [ ] O usuário deve poder filtrar a cidade pelo estado

**Comment by guilhermepupak** [comment]
Critérios de aceitação:
A US06 - Cadastro de cidades, está ok.

Obs.: Verificar juntamente com o Dirlei, na reunião de hoje, a vinculação das **Cidades** e das **Delegacias Regionais**, uma vez que cada Delegacia Regional responde por varias cidades.

**Comment by kleidson-alves** [comment]
# Roteiro para testes do usuário

História(s) a ser(em) testada(s): **US 06**

Testadores: Guilherme e Dirlei

### Passos para os testes

Para cada passo executado abaixo, **marque a caixa de seleção** correspondente para indicar a correta execução do que foi pedido.

**Obs.:** Caso seja necessário indicar mudanças ou não conformidade aos critérios de aceitação da(s) respectiva(s) história(s), responda ao presente roteiro com um comentário, marcando o "@" dos _assignees_ (MDS) e pelo menos um "@" dos EPS.

1. Acesse a aplicação em: https://schedula-2023.netlify.app/
- [ ] ok

2. Faça _login_ com as credenciais:
  * Username: test
  * Senha: test123
- [ ] ok

3. Acesse a opção de Cidades no menu lateral
- [ ] ok

4. Crie um nova cidade utilizando os dados que desejar
- [ ] ok

5. Verifique se a cidade criada apareceu na lista de cidades
- [ ] ok

6. Edite as informações de alguma cidade clicando no ícone de edição (lápis) referente a cidade que desejar 
- [ ] ok

7. Verifique se as alterações feitas na cidade foram gravadas
- [ ] ok

8. Exclua a cidade criada no passo 4, clicando no ícone de exclusão (lixeira) referente a esta cidade. 
- [ ] ok

9. Verifique se a cidade saiu da lista de cidades após clicar no botão de atualizar dados ao lado do botão de cadastrar nova cidade
- [ ] ok

10. Vá para a aba Registrar Chamado. Verifique se todas as cidades cadastradas estão presentes no campo de seleção de cidade. 
- [ ] ok  


## Testes finalizados... e agora ?

* Entre na [_issue_](https://github.com/fga-eps-mds/2022-2-Schedula-Doc/issues/35) referentes à história testada. Na descrição da US, onde há os **Critérios de Aceitação**, marque todas as caixas de seleção referente aos critérios que foram atendidos. Ou, caso contrário, faça um comentário para explicar o que está errado ou o que faltou
* Avise a equipe (pelo canal do Discord) que esse roteiro foi seguido, executado e finalizado.

## Obrigado!

Qualquer dúvida ou sugestão é só falar conosco pelo Discord.

_Template fornecido pela equipe do Alectrion! Fica nosso agradecimento para a equipe._

**Comment by guilhermepupak** [comment]
> # Roteiro para testes do usuário
> 
> História(s) a ser(em) testada(s): **US 06**
> 
> Testadores: Guilherme e Dirlei
> ### Passos para os testes
> 
> Para cada passo executado abaixo, **marque a caixa de seleção** correspondente para indicar a correta execução do que foi pedido.
> 
> **Obs.:** Caso seja necessário indicar mudanças ou não conformidade aos critérios de aceitação da(s) respectiva(s) história(s), responda ao presente roteiro com um comentário, marcando o "@" dos _assignees_ (MDS) e pelo menos um "@" dos EPS.
> 
>     1. Acesse a aplicação em: https://schedula-2023.netlify.app/
> 
> 
>     * [ok]  ok
> 
> 
>     2. Faça _login_ com as credenciais:
> 
> 
>     * Username: test
> 
>     * Senha: test123
> 
> 
>     * [ ok]  ok
> Como se trata de um sistema onde a principal função seria o cadastro de Atendimentos/Chamados, seria interessante que a tela inicial fosse a Tela de Registro de Chamados:
![image](https://user-images.githubusercontent.com/109108065/216161589-dbe47996-6e38-43dc-b9f3-821652dd1ec6.png)

> 
> 
>     3. Acesse a opção de Cidades no menu lateral
> 
> 
>     * [ok ]  ok
> 
> 
>     4. Crie um nova cidade utilizando os dados que desejar
> 
> 
>     * [ok ]  ok
> Acredito que o Estado de Goiás possa ficar gravado de forma automática, sendo possível alterar manualmente, haja vista não ter nenhum evento fora do Estado, com atribuições da Informática (DSTI):
![image](https://user-images.githubusercontent.com/109108065/216163112-f0db3ee8-9c2f-49cb-9b29-dea760c144c4.png)

> 
>     5. Verifique se a cidade criada apareceu na lista de cidades
> 
> 
>     * [ok ]  ok
> 
> 
>     6. Edite as informações de alguma cidade clicando no ícone de edição (lápis) referente a cidade que desejar
> 
> 
>     * [ok ]  ok
> 
> 
>     7. Verifique se as alterações feitas na cidade foram gravadas
> 
> 
>     * [ok ]  ok
> 
> 
>     8. Exclua a cidade criada no passo 4, clicando no ícone de exclusão (lixeira) referente a esta cidade.
> 
> 
>     * [ok ]  ok
> 
> 
>     9. Verifique se a cidade saiu da lista de cidades após clicar no botão de atualizar dados ao lado do botão de cadastrar nova cidade
> 
> 
>     * [ok ]  ok
> 
> 
>     10. Vá para a aba Registrar Chamado. Verifique se todas as cidades cadastradas estão presentes no campo de seleção de cidade.
> 
> 
>     * [ok ]  ok
> 
> 
> ## Testes finalizados... e agora ?
> 
>     * Entre na [_issue_](https://github.com/fga-eps-mds/2022-2-Schedula-Doc/issues/35) referentes à história testada. Na descrição da US, onde há os **Critérios de Aceitação**, marque todas as caixas de seleção referente aos critérios que foram atendidos. Ou, caso contrário, faça um comentário para explicar o que está errado ou o que faltou
> 
>     * Avise a equipe (pelo canal do Discord) que esse roteiro foi seguido, executado e finalizado.
> 
> 
> ## Obrigado!
> 
> Qualquer dúvida ou sugestão é só falar conosco pelo Discord.
> 
> _Template fornecido pela equipe do Alectrion! Fica nosso agradecimento para a equipe._
