### ISSUE TITLE
[US07] - Cadastro de posto de trabalho

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#36]
### Descrição:
Eu, como Alessandra, desejo poder cadastrar um novo posto de trabalho no Schedula, para permitir cadastrar chamados e agendamentos para um novo posto de trabalho.

### Tarefas:

- [ ] Endpoint para listar os postos de trabalho;
- [ ] Opções para o endpoint get para escolher os campos que deseja no retorno; 
- [ ] Endpoint para criação de um novo posto de trabalho;
- [ ] Endpoint para editar um posto de trabalho;
- [ ] Endpoint para excluir um posto de trabalho;

### Critérios de aceitação:

- Campos necessários: Nome, Cidade, Telefone, Faixa de IP, Unidade Pai, Unidades Filhas, Gateway;
- Alessandra deverá poder visualizar os postos de trabalhos cadastrados;
- Alessandra deverá poder filtrar os postos de trabalho por cidade ou unidade regional;
- Alessandra deverá poder cadastrar um novo posto de trabalho;
- Alessandra deverá poder editar um posto de trabalho;
- Alessandra deverá poder excluir um posto de trabalho (Critérios de exclusão a serem definidos)

### Tela

![image](https://user-images.githubusercontent.com/80905912/210876319-f3dd732e-5bcc-4d33-a881-7f509cb19b89.png)

Ideia de organização dos elementos da tela.

**Comment by lucas229** [comment]
# Roteiro para testes do usuário

História(s) a ser(em) testada(s): **US 07**

Testadores: Guilherme e Dirlei

### Passos para os testes

Para cada passo executado abaixo, **marque a caixa de seleção** correspondente para indicar a correta execução do que foi pedido.

**Obs.:** Caso seja necessário indicar mudanças ou não conformidade aos critérios de aceitação da(s) respectiva(s) história(s), responda ao presente roteiro com um comentário, marcando o "@" dos _assignees_ (MDS) e pelo menos um "@" dos EPS.

1. Acesse a aplicação em: https://schedula-2023.netlify.app/
- [ ] ok

2. Faça _login_ com as credenciais:
  * Username: test
  * Senha: test123
- [ ] ok

3. Acesse a opção Postos de Trabalho no menu lateral
- [ ] ok

4. Crie um novo posto de trabalho utilizando os dados que desejar
- [ ] ok

5. Verifique se o posto de trabalho criado apareceu na lista de postos de trabalho
- [ ] ok

6. Edite as informações de algum posto de trabalho clicando no ícone de edição (lápis) referente ao posto de trabalho que desejar
- [ ] ok

7. Verifique se as alterações feitas no posto de trabalho foram gravadas
- [ ] ok

8. Exclua o posto de trabalho criado no passo 4, clicando no ícone de exclusão (lixeira) referente a este posto de trabalho. 
- [ ] ok

9. Verifique se o posto de trabalho saiu da lista de postos de trabalho após clicar no botão de atualizar dados ao lado do botão de cadastrar novo posto de trabalho
- [ ] ok

10. Marque a opção Regionais e veja se somente os postos de trabalho cadastrados como regionais são listados.
- [ ] ok  

11. Acesse a opção Registrar Chamado no menu lateral. Selecione uma cidade. Verifique se todos os postos de trabalho da cidade selecionada estão presentes no campo de seleção "Posto de trabalho". 
- [ ] ok  

## Testes finalizados... e agora ?

* Entre na [_issue_](https://github.com/fga-eps-mds/2022-2-Schedula-Doc/issues/36) referentes à história testada. Na descrição da US, onde há os **Critérios de Aceitação**, marque todas as caixas de seleção referente aos critérios que foram atendidos. Ou, caso contrário, faça um comentário para explicar o que está errado ou o que faltou
* Avise a equipe (pelo canal do Discord) que esse roteiro foi seguido, executado e finalizado.

## Obrigado!

Qualquer dúvida ou sugestão é só falar conosco pelo Discord.

_Template fornecido pela equipe do Alectrion! Fica nosso agradecimento para a equipe._

**Comment by guilhermepupak** [comment]
> # Roteiro para testes do usuário
> 
> História(s) a ser(em) testada(s): **US 07**
> 
> Testadores: Guilherme e Dirlei
> ### Passos para os testes
> 
> Para cada passo executado abaixo, **marque a caixa de seleção** correspondente para indicar a correta execução do que foi pedido.
> 
> **Obs.:** Caso seja necessário indicar mudanças ou não conformidade aos critérios de aceitação da(s) respectiva(s) história(s), responda ao presente roteiro com um comentário, marcando o "@" dos _assignees_ (MDS) e pelo menos um "@" dos EPS.
> 
>     1. Acesse a aplicação em: https://schedula-2023.netlify.app/
> 
> 
>     * [ok ]  ok
> 
> 
>     2. Faça _login_ com as credenciais:
> 
> 
>     * Username: test
> 
>     * Senha: test123
> 
> 
>     * [ok ]  ok
> 
> 
>     3. Acesse a opção Postos de Trabalho no menu lateral
> 
> 
>     * [ok ]  ok
> 
> 
>     4. Crie um novo posto de trabalho utilizando os dados que desejar
> 
> 
>     * [ ]  ok
> 
> 
>     5. Verifique se o posto de trabalho criado apareceu na lista de postos de trabalho
> 
> 
>     * [ ]  ok
> 
> 
>     6. Edite as informações de algum posto de trabalho clicando no ícone de edição (lápis) referente ao posto de trabalho que desejar
> 
> 
>     * [ ]  ok
> 
> 
>     7. Verifique se as alterações feitas no posto de trabalho foram gravadas
> 
> 
>     * [ ]  ok
> 
> 
>     8. Exclua o posto de trabalho criado no passo 4, clicando no ícone de exclusão (lixeira) referente a este posto de trabalho.
> 
> 
>     * [ ]  ok
> 
> 
>     9. Verifique se o posto de trabalho saiu da lista de postos de trabalho após clicar no botão de atualizar dados ao lado do botão de cadastrar novo posto de trabalho
> 
> 
>     * [ ]  ok
> 
> 
>     10. Marque a opção Regionais e veja se somente os postos de trabalho cadastrados como regionais são listados.
> 
> 
>     * [ ]  ok
> 
> 
>     11. Acesse a opção Registrar Chamado no menu lateral. Selecione uma cidade. Verifique se todos os postos de trabalho da cidade selecionada estão presentes no campo de seleção "Posto de trabalho".
> 
> 
>     * [ ]  ok
> 
> 
> ## Testes finalizados... e agora ?
> 
>     * Entre na [_issue_](https://github.com/fga-eps-mds/2022-2-Schedula-Doc/issues/36) referentes à história testada. Na descrição da US, onde há os **Critérios de Aceitação**, marque todas as caixas de seleção referente aos critérios que foram atendidos. Ou, caso contrário, faça um comentário para explicar o que está errado ou o que faltou
> 
>     * Avise a equipe (pelo canal do Discord) que esse roteiro foi seguido, executado e finalizado.
> 
> 
> ## Obrigado!
> 
> Qualquer dúvida ou sugestão é só falar conosco pelo Discord.
> 
> _Template fornecido pela equipe do Alectrion! Fica nosso agradecimento para a equipe._

**Comment by guilhermepupak** [comment]
> # Roteiro para testes do usuário
> 
> História(s) a ser(em) testada(s): **US 07**
> 
> Testadores: Guilherme e Dirlei
> ### Passos para os testes
> 
> Para cada passo executado abaixo, **marque a caixa de seleção** correspondente para indicar a correta execução do que foi pedido.
> 
> **Obs.:** Caso seja necessário indicar mudanças ou não conformidade aos critérios de aceitação da(s) respectiva(s) história(s), responda ao presente roteiro com um comentário, marcando o "@" dos _assignees_ (MDS) e pelo menos um "@" dos EPS.
> 
>     1. Acesse a aplicação em: https://schedula-2023.netlify.app/
> 
> 
>     * [ok ]  ok
> 
> 
>     2. Faça _login_ com as credenciais:
> 
> 
>     * Username: test
> 
>     * Senha: test123
> 
> 
>     * [ok ]  ok
> 
> 
>     3. Acesse a opção Postos de Trabalho no menu lateral
> 
> 
>     * [ok ]  ok
> 
> 
>     4. Crie um novo posto de trabalho utilizando os dados que desejar
> 
> 
>     * [RESSALVA]  ok
![image](https://user-images.githubusercontent.com/109108065/216338046-38565c6c-83b4-455a-85f1-7778b867f998.png)
 
> 
>     5. Verifique se o posto de trabalho criado apareceu na lista de postos de trabalho
> 
> 
>     * [OK ]  ok
> 
> 
>     6. Edite as informações de algum posto de trabalho clicando no ícone de edição (lápis) referente ao posto de trabalho que desejar
> 
> 
>     * [OK ]  ok
> 
> 
>     7. Verifique se as alterações feitas no posto de trabalho foram gravadas
> 
> 
>     * [OK ]  ok
> 
> 
>     8. Exclua o posto de trabalho criado no passo 4, clicando no ícone de exclusão (lixeira) referente a este posto de trabalho.
> 
> 
>     * [OK ]  ok
> 
> 
>     9. Verifique se o posto de trabalho saiu da lista de postos de trabalho após clicar no botão de atualizar dados ao lado do botão de cadastrar novo posto de trabalho
> 
> 
>     * [OK ]  ok
> 
> 
>     10. Marque a opção Regionais e veja se somente os postos de trabalho cadastrados como regionais são listados.
> 
> 
>     * [RESSALVA ]  ok
![image](https://user-images.githubusercontent.com/109108065/216338580-21664be9-bbac-4c5b-8d4f-3dbe709d0ace.png)

> 
> 
>     11. Acesse a opção Registrar Chamado no menu lateral. Selecione uma cidade. Verifique se todos os postos de trabalho da cidade selecionada estão presentes no campo de seleção "Posto de trabalho".
> 
> 
>     * [OK ]  ok
> 
> 
> ## Testes finalizados... e agora ? 
> 
>     * Entre na [_issue_](https://github.com/fga-eps-mds/2022-2-Schedula-Doc/issues/36) referentes à história testada. Na descrição da US, onde há os **Critérios de Aceitação**, marque todas as caixas de seleção referente aos critérios que foram atendidos. Ou, caso contrário, faça um comentário para explicar o que está errado ou o que faltou
> 
>     * Avise a equipe (pelo canal do Discord) que esse roteiro foi seguido, executado e finalizado.
> 
> 
> ## Obrigado!
> 
> Qualquer dúvida ou sugestão é só falar conosco pelo Discord.
> 
> _Template fornecido pela equipe do Alectrion! Fica nosso agradecimento para a equipe._
