### ISSUE TITLE
[US10] - Status de Agendamento

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#39]
### Descrição:
Eu, como Técnico, desejo poder alterar o status de um agendamento, para	conseguir definir um agendamento como concluído ou não.

### Tarefas:

- [ ] Linkar esta issue no PR que será aberto;

### Critérios de aceitação:
- [ ] O técnico deverá poder alterar o status de um agendamento.
- [ ] As opções de status devem ser: NÃO RESOLVIDO; EM ANDAMENTO; PENDENTE; URGENTE e RESOLVIDO
- [ ] Um agendamento não deverá ter mais de 1 status no mesmo momento

**Comment by guilhermepupak** [comment]
Critérios de aceitação:
US10 - Status de Agendamento, esta ok.
